Extracted job title info from historical data
data-engineering-community/data-engineering-salaries pull request #11
Opened 2023-10-26 21:00 UTC by apuhegde

Working modular version of job title script.

2023-11-01 03:40 UTC, JPHaus requested changes
I requested removing the metadata files but otherwise the code is a solid contribution!

2023-11-01 03:40 UTC, JPHaus commented on archive/job_title.py
> +    body_df[colname] = body_df[colname].str.replace("^[ ]?1[.:)][ ]?","",regex=True)
Great job on the regex!

2023-11-01 03:40 UTC, JPHaus commented on .streamlit/example.secrets.toml
We need this example file - would you mind adding it back?

2023-11-01 03:40 UTC, JPHaus commented on .gitignore
Updated the .gitignore to ignore the metadata files/folders.

2023-11-01 03:40 UTC, JPHaus commented on archive/extract_historical_data.py
> +        json_files.append(os.path.join(input_dir, file))
```suggestion
import glob

json_files = glob.glob(os.path.join(input_dir, '*.json'))
```
This way is completely fine and understandable I just wanted to show an alternate way of getting all of the files in a directory.

2023-11-14 04:02 UTC, apuhegde commented on .gitignore
Sounds good.

2023-11-14 04:07 UTC, apuhegde commented on .streamlit/example.secrets.toml
Done.

2023-11-14 06:35 UTC, suleman1412 commented
This looks amazing. Very well done @apuhegde on the regex. I wanted to know if creating a function would be a better way to write the code or would it just take more time to call a function and return a value. For example, we can make a function to replace special characters?

2023-11-23 06:49 UTC, JPHaus approved these changes
Sorry this took so long - thanks again for this great contribution and happy Thanksgiving @apuhegde!

2023-11-23 06:49 UTC, merged